Leaders:
    Rafaelos_:
        gym16: {'[Tue May 11 22:32:11 BRT 2021]': ChapiscandoYT - Won, '[11-05-2021 (12:01:16)]': D4bjk
                - Lost}
Challengers:
    17627af0-198d-329e-a580-6b3fcd5a47b3:
        gym16: {Date/Time Won: '[Tue May 11 22:32:11 BRT 2021]', Gym Leader: Rafaelos_}
